name: build-docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Login to Docker Image Registry
      uses: docker/login-action@v3
      if: ${{ env.DOCKER_HUB_LOGIN && env.DOCKER_HUB_PASSWORD }}
      with:
        username: "${{ secrets.DOCKER_HUB_LOGIN }}"
        password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: make docker docker-publish
      env:
        DOCKER_REPO: ghcr.io/${{ github.repository }}
        DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}
    - run: make docker docker-publish
      env:
        DOCKER_REPO: ghcr.io/${{ github.repository }}
        DOCKER_IMAGE_TAG: latest
